# run: conda env create --file environment.yml
name: tsp
channels:
- pytorch
dependencies:
- python>=3.8
- anaconda
- tqdm
- pytorch
- torchvision
- cuda91
- pip
- pip:
  - tensorboard_logger
  - tensorflow
  - wandb
  - loguru
